name: Daily Zoho Reports

on:
  schedule:
    - cron: '30 2 * * *' # 08:00 AM IST
  workflow_dispatch: # Allows you to run it manually

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
        
      - name: Run Main Script
        env:
          ZOHO_AUTH_JSON: ${{ secrets.ZOHO_AUTH_JSON }} # THIS LINE IS CRITICAL
        run: Rscript main.R
